/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.kaabhis.bulk;

import org.kaabhis.bulk.datacreator.DataService;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        try {
            DataService service = new DataService(true);
            service.initStreams();

            Thread.currentThread().join();

        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        System.out.println("Application End!");
    }
}
